name: Update Pixelsports Playlist

on:
  schedule:
    # Runs every 6 hours (at 00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'
  
  # Allows manual trigger from Actions tab
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Run Pixelsports script
        run: python pixelsports.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add Pixelsports.m3u8
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update playlist - $(date -u '+%Y-%m-%d %H:%M:%S UTC')" && git push)
